---
- name: Take VM Snapshots for Multiple VMs
  hosts: all
  become: yes
  vars:
    vcenter_hostname: "192.168.1.70"
    vcenter_username: "root"
    vcenter_password: "kharian@82"
    folder: "datastore1"
    snapshot_prefix: "VM_SnapshotVA"

  tasks:
    - name: Define VM hosts and details
      set_fact:
        vm_hosts:
          - { name: 'vm1', ip: '192.168.1.202' }
   - name: Loop through each VM host and create a snapshot
      vmware_guest_snapshot:
        hostname: "{{ 192.168.1.72 }}"
        username: "{{ root }}"
        password: "{{ kharian@82}}"
        validate_certs: no
        folder: "{{ datastore1 }}"
        name: "{{ VM_SnapshotVA }}"
        snapshot_name: "{{ VM_SnapshotVA }}_{{ VM_SnapshotVA }}_snapshot"
        memory: no
        state: present
      with_items: "{{ vm_hosts }}"
      delegate_to: localhost
