---
- name: Take VM Snapshots for Multiple VMs
  hosts: all
  become: yes
  tasks:
    - name: Define VM hosts and details
      set_fact:
        vm_hosts:
          - { name: 'vm1', ip: '192.168.1.202' }
          - { name: 'vm2', ip: '192.168.1.72' }
          - { name: 'vm3', ip: '192.168.1.73' }

    - name: Loop through each VM host and create a snapshot
      vmware_guest_snapshot:
        hostname: "192.168.1.70"
        username: "root"
        password: "kharian@82"
        validate_certs: no
        folder: "datastore1"
        name: "{{ item.name }}"
        snapshot_name: "{{ item.name }}_snapshot"
        memory: no
        state: present
      with_items: "{{ vm_hosts }}"
      delegate_to: localhost
