---
- name: Take VM Snapshots for Multiple VMs
  hosts: all
  become: yes
  vars:
    vcenter_hostname: "192.168.1.70"
    vcenter_username: "root"
    vcenter_password: "kharian@82"
    folder: "datastore1"
    snapshot_prefix: "VM_SnapshotVA"

  tasks:
    - name: Define VM hosts and details
      set_fact:
        vm_hosts:
          - { name: 'vm1', ip: '192.168.1.202' }
          - { name: 'vm2', ip: '192.168.1.72' }
          - { name: 'vm3', ip: '192.168.1.73' }
   - name: Loop through each VM host and create a snapshot
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: "{{ item.name }}"
        snapshot_name: "{{ snapshot_prefix }}_{{ item.name }}_snapshot"
        memory: no
        state: present
      with_items: "{{ vm_hosts }}"
      delegate_to: localhost
