---
- name: Take VM Snapshot for a Single VM
  hosts: localhost
  become: yes
  vars:
    vcenter_hostname: "192.168.1.70"
    vcenter_username: "root"
    vcenter_password: "kharian@82"
    folder: "[datastore1] snapshots/"
    snapshot_prefix: "VM_SnapshotVA"

  tasks:
    - name: Create a snapshot for the specified VM
      vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: "{{ folder }}"
        name: 'vm1'  # Name of the VM for the IP 192.168.1.202
        snapshot_name: "{{ snapshot_prefix }}_vm1_snapshot"
        memory: no
        state: present
      delegate_to: localhost
